amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIASTMTRDMNYJSHEH5E
  secretKey: 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
  bucketName: test-upload-argano
 
spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB