amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: user_access_key
  secretKey: user_secret_key
  bucketName: bucket_name
 
spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
